version: '3.9'

services:
  database:
    image: postgres:15
    ports:
      - "5436:5436"
    command: -p 5436
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379
  
  web:
    build: .
    image: web:latest
    command: sh -c "./scripts/django.sh"
    volumes:
      - .:/app # sync with docker with local folders 
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

  nginx:
    build: ./nginx
    volumes:
      - .:/app # sync with docker with local folders 
    ports:
      - "80:80"
    depends_on:
      - web

  celery:
    build: .
    image: celery:0.1
    container_name: celery
    volumes:
      - .:/app
    command: celery -A media_stream worker -l INFO -Q celery,high --pool=solo
    depends_on:
      - web
  

  # # http://localhost:5050/
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      
    ports:
      - "5050:80"
    volumes:
      - pgadmin_volumne:/var/lib/pgadmin

volumes:
  postgres_volume:
  pgadmin_volumne:  
