# Generated by Django 4.0.5 on 2022-07-09 06:54

from django.db import migrations, models
import django.db.models.deletion
import video_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_lang', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('category_name', 'category_lang')},
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_title_slug', models.SlugField(blank=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_file_name', models.FileField(upload_to=video_app.models.USER_DIRECTORY_PATH)),
                ('video_file_m3u8', models.CharField(blank=True, max_length=255)),
                ('video_thumbnail', models.ImageField(upload_to=video_app.models.USER_DIRECTORY_PATH)),
                ('video_released_date', models.DateField()),
                ('video_uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('video_processing_status', models.IntegerField(choices=[(-1, 'Failed'), (0, 'Queued'), (1, 'Started'), (2, 'Finished')], default=0)),
                ('video_error_msg', models.TextField(blank=True, null=True)),
                ('video_processing_completed', models.DateTimeField(blank=True, null=True)),
                ('video_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.categorymodel')),
            ],
        ),
    ]
