# Generated by Django 4.0.9 on 2023-03-22 16:20

from django.db import migrations, models
import django.db.models.deletion
import video_app.mixins
import video_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_name_slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('m3u8_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to=video_app.models.STORE_TV_THUMBNAIL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.categorymodel')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.languagemodel')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('channel_name', 'language')},
            },
            bases=(models.Model, video_app.mixins.ModelCacheMixin),
        ),
    ]
